// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RBTemplate.Infra.CrossCutting.Identity.Data;

namespace RBTemplate.Infra.CrossCutting.Identity.Migrations.RefreshToken
{
    [DbContext(typeof(RefreshTokenContext))]
    [Migration("20191231004032_InitialRefreshToken")]
    partial class InitialRefreshToken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RBTemplate.Infra.CrossCutting.Identity.Authorization.RefreshTokenData", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnName("UsuarioId")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("RefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
